kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-production-canary
  labels:
    app: app-production-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
        env: canary
    spec:
      containers:
        - name: app
          image: vleclercdev/test-node-prestashop:0.0.2
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          ports:
          - name: app
            containerPort: 3000
          env:
          - name: NODE_ENV
            value: production
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name